title: C 語言指標完全教學
description: 深入淺出學會 C 語言指標，從基礎到進階的完整教學
author: yehchuntin
email: 2017yehchunting@gamil.com
url: "https://yehchuntin.github.io"

markdown: kramdown
highlighter: rouge
theme: minima
timezone: Asia/Taipei

paginate: 10
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

header_pages:
  - about.md

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

excerpt_separator: <!--more-->
